### ISSUE TITLE
Many feature requests.

### ISSUE THREAD

**Issue by RDKRACZ** [unascribed/Fabrication#66]
I will check if any of these are already added and update this.
01. Sneak through Sweet Berry Bushes without taking damage
02. You take damage on magma blocks even while sneaking
03. If a skeleton is on fire it will have a chance to shoot a flaming arrow. Flaming arrows will cause some burning damage if they hit you (70% chance by default)
04. Sleeping in a bed will heal the player by a configurable amount
05. Sleeping will cure negative and positive potion effects
06. Fix fire damage not always giving cooked drops caused by inconsistency with how loot tables check if the mob was on fire. The vanilla mechanic only checks for "damage over time" fire damage and not instant fire damage. This has lead to many edge cases where things like the vanilla Camp Fire block and various fire mechanics in other mods will not cause mobs to drop the correct items
07. Expand the vanilla feature that allows zombies to spread fire to their targets if they attack without an item to all mobs
08. Strippable blocks can be stripped in a crafting table with an axe
09. Concrete powder can be solidified in a crafting table with a water bucket
10. The glass bottle received after drinking a potion will automatically be moved into an already existing stack of glass bottles in your inventory (if available)
11. Chests can be opened through item frames, causing the item not to be rotated. Sneaking will use the default behavior
12. Chests can be opened through signs
13. When a lead breaks a sound is played
14. Leadable Hoglins, Zoglins, Turtles, Pandas
15. Slab placed on top of a slab doesn't look like a full block
16. Allow nylium and roots to spread in the Nether like grass does in the Overworld
17. Entities ignited by soul fire will have blue fire effects instead of normal fire
18. Entities ignited by soul fire take twice as much damage as those ignited by regular fire
19. Chickens, cows, horses, pigs, sheep, and wolves will eat off the ground. Drop food to breed them
20. Wild wolves are able to be bred. Allow for some neat natural systems
21. Plants that fall on dirt or grass will automatically plant. Applies to saplings, wheat seeds, pumpkin seeds, melon seeds, beetroot seeds, carrots, and potatoes
22. Make grass and long grass spread naturally over time
23. Remove hitboxes from long grass. Hitboxes are shown when using shears. Seeds can be gathered by using a hoe on the ground below them
24. Make leaves passable by removing collision from them
25. Leaves decay fast when outside the range of a log block
26. Allow boats to pass through lily pads without breaking them. Also allows entities to rise through the bottom of a lily pad
27. Farmer villagers will deposit excess items into a nearby chest
28. When a log on fire burns, it drops A charcoal (Also makes charcoal fireproof)
29. Doors and trapdoors open adjacent doors and trapdoors of the same type. Works when opened by hand or with Redstone
30. Right-click signs to edit text
31. Destroyed signs preserves text
32. Right-click a Cauldron with a Heart of the Sea to create an infinite water source
33. XP sources give their XP directly to the player that earns them (other than the Ender Dragon). This would reduce lag on big servers
34. The heads of tipped arrows render the color of their status effect
35. Cobblestone and stone brick blocks, slabs, stairs, and walls will turn mossy when in rain or surrounded by water and will dry out again when in sunlight
36. Cauldrons can't be filled with water in the Nether
37. Falling into a water-filled cauldron will save you from fall damage just like normal water
38. Fix water in cauldrons rendering as opaque. Make water render as translucent as intended
39. Fix end portals only rendering from above
40. Remove the glowing effect from potions, this will make potion colors more visible
41. Disable the warning that displays when loading a world that uses experimental settings
42. Allow zombies to break wooden doors placed in all directions - https://youtube.com/watch?v=jQJL2L_clvE
43. Projectiles can break glass
44. Spawn eggs can be thrown
45. Disable random chicken egg-laying. Instead, chickens will lay one or two eggs when breeding
46. Increase the chance of spawning a chicken when throwing an egg to 80%
47. Chickens drop feathers randomly.
48. Zombies can break doors on the normal and easy difficulty.

**Comment by unascribed** [comment]
275ac1a1e0290fa8e600e617c6fa5c258e3f5fb7

Please pick 6 or so of these that you really want and make individual issues for them.

**Comment by RDKRACZ** [comment]
I will open new issues for the best features from these. A few new ones after You decide if you want or not something from these I opened for now.
